### ISSUE TITLE
Error trying to request the receipt or the invoice

### ISSUE THREAD

**Issue by cougil** [alfio-event/alf.io#383] opened 2018-02-04 20:35 UTC
Hi.

As a user I've tried to request the invoice or the receipt related with the payment done (using the Sandbox for both Paypal and Stripe), but the link ("Download your receipt/invoice") does not work (even the receipt is attached in confirmation email). Here you can see the exception thrown:

```
 [qtp985679444-265] ERROR alfio.controller.ControllerExceptionHandler - unexpected exception
java.lang.IllegalStateException: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of alfio.model.OrderSummary: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: {"originalTotalPrice":{"priceWithVAT":18150,"discount":0,"discountAppliedCount":0,"vat":3150},"summary":[{"name":"early","price":"150.00","priceBeforeVat":"150.00","amount":1,"subTotal":"150.00","subTotalBeforeVat":"150.00","originalSubTotal":15000,"type":"TICKET"}],"free":false,"totalPrice":"181.50","totalVAT":"31.50","waitingForPayment":false,"cashPayment":false,"vatPercentage":"12345678G","vatStatus":null,"ticketAmount":1,"displayVat":true,"notYetPaid":false,"singleTicketOrder":true}; line: 1, column: 2]
        at alfio.util.Json.fromJson(Json.java:57) ~[main/:?]
        at alfio.controller.InvoiceReceiptController.buildDocument(InvoiceReceiptController.java:71) ~[main/:?]
        at alfio.controller.InvoiceReceiptController.lambda$getInvoice$6(InvoiceReceiptController.java:114) ~[main/:?]
        at alfio.controller.InvoiceReceiptController.lambda$null$0(InvoiceReceiptController.java:66) ~[main/:?]
```

Best regards,

**Comment by syjer** [comment] 2018-02-04 21:01
hi @cougil , which release are you using? 

We have noticed that after upgrading jackson, some of his default behaviour has changed.

**Comment by syjer** [comment] 2018-02-05 01:01
@cougil I can confirm that this issue affect the master, but not the stable branch.

I'll have a look at what could be the root cause.

**Comment by syjer** [comment] 2018-02-05 13:22
I confirm that the issue is the upgrade from lombok lombok:1.16.16 to lombok:1.16.20. It seems that the generated code has changed (most likely it does not generate anymore the constructor??)

**Comment by syjer** [comment] 2018-02-05 13:38
should be fixed now. Remember to do a clean of the workspace :D

**Closed by syjer** 2018-02-05 13:38 UTC
Labels: bug

**Comment by cougil** [comment] 2018-02-05 14:38
Thank you very much for your quick reply! ;-)
About the resolution, I have not understood the point about the 'stable branch'. It is not 'master'? Which branch should we use for 'production' ?

**Comment by syjer** [comment] 2018-02-05 14:41
@cougil for production you should use one the latest release listed at https://github.com/alfio-event/alf.io/releases :)
