### ISSUE TITLE
Scan app: Invalid QR code

### ISSUE THREAD

**Issue by icougil** [alfio-event/alf.io#1346] opened 2024-03-26 18:48 UTC
**Describe the bug**
If you try to scan any QR code from any ticket, the application does not recognize it.

**To Reproduce**
1. Open the mobile app
2. Setup the "Sponsor user" via API keys in the backoffice
3. Add it in the app accordingly (capture it via QR code)
4. Select the event you are interested into
5. Click on Scan button
6. See error "Invalid code"

**Expected behavior**
The ticket information should be loaded in the mobile app

**Screenshots**
?? The mobile app only shows "Invalid code" when trying to load the image

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 11
 - Browser: N/A

**Additional context**
N/A

**Comment by cbellone** [comment] 2024-03-29 09:42
Hi,

only check-in operators / supervisors are able to scan tickets through the app.
Sponsors can only scan badges.

So if you want to use the mobile app for lead collection, you should print badges using [Alf.io-PI](https://github.com/alfio-event/alf.io-PI) [relevant documentation](https://alf.io/docs/event-management/check-in/stations/)

I am going to close this since it's not a bug. Please feel free to start a [discussion](https://github.com/alfio-event/alf.io/discussions) if you have further questions

**Closed by cbellone** 2024-03-29 09:42 UTC
Labels: question

**Comment by icougil** [comment] 2024-03-31 15:49
Hi Celestino,

Just to confirm: the QR code in the tickets is incompatible with the App you provide for badge scanning, and we should use the Alf.io-PI alternative to print the proper badges. Is that correct?

Best,
