### ISSUE TITLE
Required field configuration causing error on sign-up

### ISSUE THREAD

**Issue by bottlebug** [alfio-event/alf.io#737] opened 2019-09-02 22:53 UTC
**Describe the bug**
If an event has a field which is required but only has 'Collect for' on some ticket categories, if a customer tries to purchase a ticket which isn't one of those categories, they will be prompted with an error saying "Please fill attendees' details" (even though all visible fields have been completed)

**Expected behavior**
The customer should be able to purchase the ticket without seeing the error.

I suspect that the ticket data row is making the field required regardless of what the ticket category is, thus preventing the ticket from being created.

**Screenshots**
![image](https://user-images.githubusercontent.com/16513636/64135045-a8620f80-ce38-11e9-9e09-f3cb5f9036f3.png)

**Comment by cbellone** [comment] 2019-09-03 06:15
Hi @bottlebug 

which version are you using? 
As far as I know we have fixed this regression in [2.0-M1-1907](https://github.com/alfio-event/alf.io/releases/tag/2.0-M1-1907)

**Comment by cbellone** [comment] 2019-09-03 07:44
UPDATE: we've found that the issue is still present. We'll provide a new version asap

**Comment by syjer** [comment] 2019-09-03 20:36
@bottlebug , we have re-checked, that specific regression has been indeed fixed in the release 2.0-M1-1907. Could you please check the version that you are using :)

**Closed** 2019-09-05 13:35 UTC
Labels: bug
